/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */

 description="""
 Example Gradle Project demonstarting the gradle build for a java application
 project name: $(project.name)
 """

  plugins{
       // Apply plugins
       application
    }  

 repositories{
       // use mavon repo
       mavenCentral()
    }

  dependencies{
       "implementation"("org.testng:testng:7.4.0")
    "implementation"("com.google.guava:guava:30.0-jre")      
    }

    application{
        //define the main class 
        mainClass.set("GradleDemo.App")
    }

tasks.test{
  //useTestNG
   useTestNG()
}

